USE [master]
GO
/****** Object:  Database [VendingDB]    Script Date: 15.02.2026 21:56:09 ******/
CREATE DATABASE [VendingDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'VendingDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.SQLEXPRESS\MSSQL\DATA\VendingDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'VendingDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.SQLEXPRESS\MSSQL\DATA\VendingDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [VendingDB] SET COMPATIBILITY_LEVEL = 170
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [VendingDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [VendingDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [VendingDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [VendingDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [VendingDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [VendingDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [VendingDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [VendingDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [VendingDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [VendingDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [VendingDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [VendingDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [VendingDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [VendingDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [VendingDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [VendingDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [VendingDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [VendingDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [VendingDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [VendingDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [VendingDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [VendingDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [VendingDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [VendingDB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [VendingDB] SET  MULTI_USER 
GO
ALTER DATABASE [VendingDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [VendingDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [VendingDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [VendingDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [VendingDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [VendingDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [VendingDB] SET OPTIMIZED_LOCKING = OFF 
GO
ALTER DATABASE [VendingDB] SET QUERY_STORE = ON
GO
ALTER DATABASE [VendingDB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [VendingDB]
GO
/****** Object:  Table [dbo].[Country]    Script Date: 15.02.2026 21:56:09 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Country](
	[CountryID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](100) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CountryID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Events]    Script Date: 15.02.2026 21:56:09 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Events](
	[EventID] [int] IDENTITY(1,1) NOT NULL,
	[MachineID] [int] NULL,
	[EventType] [nvarchar](20) NOT NULL,
	[Message] [nvarchar](255) NOT NULL,
	[EventDateTime] [datetime2](7) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[EventID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MachineProducts]    Script Date: 15.02.2026 21:56:09 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MachineProducts](
	[MachineID] [int] NOT NULL,
	[ProductID] [int] NOT NULL,
	[Quantity] [int] NOT NULL,
 CONSTRAINT [PK_MachineProducts] PRIMARY KEY CLUSTERED 
(
	[MachineID] ASC,
	[ProductID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MachineStatus]    Script Date: 15.02.2026 21:56:09 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MachineStatus](
	[StatusID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[StatusID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Maintenance]    Script Date: 15.02.2026 21:56:09 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Maintenance](
	[NoteID] [int] IDENTITY(1,1) NOT NULL,
	[MachineID] [int] NOT NULL,
	[MaintenanceDate] [date] NOT NULL,
	[Description] [nvarchar](500) NOT NULL,
	[Problems] [nvarchar](500) NULL,
	[DoneByUserID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[NoteID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PaymentType]    Script Date: 15.02.2026 21:56:09 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PaymentType](
	[PaymentTypeID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](30) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[PaymentTypeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Products]    Script Date: 15.02.2026 21:56:09 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Products](
	[ProductID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](100) NOT NULL,
	[Description] [nvarchar](255) NULL,
	[Price] [decimal](10, 2) NOT NULL,
	[InStock] [int] NOT NULL,
	[MinStock] [int] NOT NULL,
	[PropensityToSell] [decimal](6, 2) NULL,
PRIMARY KEY CLUSTERED 
(
	[ProductID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Sales]    Script Date: 15.02.2026 21:56:09 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Sales](
	[SaleID] [int] IDENTITY(1,1) NOT NULL,
	[MachineID] [int] NOT NULL,
	[ProductID] [int] NOT NULL,
	[Quantity] [int] NOT NULL,
	[SaleSum] [decimal](10, 2) NOT NULL,
	[SaleDateTime] [datetime2](7) NOT NULL,
	[PaymentTypeID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[SaleID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 15.02.2026 21:56:09 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[UserID] [int] IDENTITY(1,1) NOT NULL,
	[FullName] [nvarchar](150) NOT NULL,
	[Contacts] [nvarchar](120) NOT NULL,
	[Role] [nvarchar](50) NOT NULL,
	[Password] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[UserID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Contacts] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[VendingMachines]    Script Date: 15.02.2026 21:56:09 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[VendingMachines](
	[MachineID] [int] IDENTITY(1,1) NOT NULL,
	[Location] [nvarchar](255) NOT NULL,
	[Model] [nvarchar](100) NOT NULL,
	[PaymentTypeID] [int] NOT NULL,
	[FullIncome] [decimal](12, 2) NOT NULL,
	[SerialNumber] [nvarchar](100) NOT NULL,
	[InventoryNumber] [nvarchar](100) NOT NULL,
	[Manufacturer] [nvarchar](100) NOT NULL,
	[ManufactureDate] [date] NOT NULL,
	[InsertDate] [date] NOT NULL,
	[DateOfCommissioning] [date] NOT NULL,
	[LastVerificationDate] [date] NOT NULL,
	[VerificationInterval] [int] NULL,
	[ResourceHours] [int] NOT NULL,
	[DateOfNextFixing] [date] NOT NULL,
	[MaintenanceTimeHours] [int] NOT NULL,
	[MachineStatusID] [int] NOT NULL,
	[CountryID] [int] NOT NULL,
	[InventoryDate] [date] NOT NULL,
	[LastCheckedByUserID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[MachineID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[SerialNumber] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[InventoryNumber] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Events] ADD  DEFAULT (getdate()) FOR [EventDateTime]
GO
ALTER TABLE [dbo].[Sales] ADD  DEFAULT (getdate()) FOR [SaleDateTime]
GO
ALTER TABLE [dbo].[VendingMachines] ADD  DEFAULT ((0)) FOR [FullIncome]
GO
ALTER TABLE [dbo].[VendingMachines] ADD  DEFAULT (CONVERT([date],getdate())) FOR [InsertDate]
GO
ALTER TABLE [dbo].[Events]  WITH CHECK ADD  CONSTRAINT [FK_Event_Machine] FOREIGN KEY([MachineID])
REFERENCES [dbo].[VendingMachines] ([MachineID])
GO
ALTER TABLE [dbo].[Events] CHECK CONSTRAINT [FK_Event_Machine]
GO
ALTER TABLE [dbo].[MachineProducts]  WITH CHECK ADD  CONSTRAINT [FK_MP_Machine] FOREIGN KEY([MachineID])
REFERENCES [dbo].[VendingMachines] ([MachineID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[MachineProducts] CHECK CONSTRAINT [FK_MP_Machine]
GO
ALTER TABLE [dbo].[MachineProducts]  WITH CHECK ADD  CONSTRAINT [FK_MP_Product] FOREIGN KEY([ProductID])
REFERENCES [dbo].[Products] ([ProductID])
GO
ALTER TABLE [dbo].[MachineProducts] CHECK CONSTRAINT [FK_MP_Product]
GO
ALTER TABLE [dbo].[Maintenance]  WITH CHECK ADD  CONSTRAINT [FK_Maint_Machine] FOREIGN KEY([MachineID])
REFERENCES [dbo].[VendingMachines] ([MachineID])
GO
ALTER TABLE [dbo].[Maintenance] CHECK CONSTRAINT [FK_Maint_Machine]
GO
ALTER TABLE [dbo].[Maintenance]  WITH CHECK ADD  CONSTRAINT [FK_Maint_User] FOREIGN KEY([DoneByUserID])
REFERENCES [dbo].[Users] ([UserID])
GO
ALTER TABLE [dbo].[Maintenance] CHECK CONSTRAINT [FK_Maint_User]
GO
ALTER TABLE [dbo].[Sales]  WITH CHECK ADD  CONSTRAINT [FK_Sales_Machine] FOREIGN KEY([MachineID])
REFERENCES [dbo].[VendingMachines] ([MachineID])
GO
ALTER TABLE [dbo].[Sales] CHECK CONSTRAINT [FK_Sales_Machine]
GO
ALTER TABLE [dbo].[Sales]  WITH CHECK ADD  CONSTRAINT [FK_Sales_Payment] FOREIGN KEY([PaymentTypeID])
REFERENCES [dbo].[PaymentType] ([PaymentTypeID])
GO
ALTER TABLE [dbo].[Sales] CHECK CONSTRAINT [FK_Sales_Payment]
GO
ALTER TABLE [dbo].[Sales]  WITH CHECK ADD  CONSTRAINT [FK_Sales_Product] FOREIGN KEY([ProductID])
REFERENCES [dbo].[Products] ([ProductID])
GO
ALTER TABLE [dbo].[Sales] CHECK CONSTRAINT [FK_Sales_Product]
GO
ALTER TABLE [dbo].[VendingMachines]  WITH CHECK ADD  CONSTRAINT [FK_VM_Country] FOREIGN KEY([CountryID])
REFERENCES [dbo].[Country] ([CountryID])
GO
ALTER TABLE [dbo].[VendingMachines] CHECK CONSTRAINT [FK_VM_Country]
GO
ALTER TABLE [dbo].[VendingMachines]  WITH CHECK ADD  CONSTRAINT [FK_VM_Payment] FOREIGN KEY([PaymentTypeID])
REFERENCES [dbo].[PaymentType] ([PaymentTypeID])
GO
ALTER TABLE [dbo].[VendingMachines] CHECK CONSTRAINT [FK_VM_Payment]
GO
ALTER TABLE [dbo].[VendingMachines]  WITH CHECK ADD  CONSTRAINT [FK_VM_Status] FOREIGN KEY([MachineStatusID])
REFERENCES [dbo].[MachineStatus] ([StatusID])
GO
ALTER TABLE [dbo].[VendingMachines] CHECK CONSTRAINT [FK_VM_Status]
GO
ALTER TABLE [dbo].[VendingMachines]  WITH CHECK ADD  CONSTRAINT [FK_VM_User] FOREIGN KEY([LastCheckedByUserID])
REFERENCES [dbo].[Users] ([UserID])
GO
ALTER TABLE [dbo].[VendingMachines] CHECK CONSTRAINT [FK_VM_User]
GO
ALTER TABLE [dbo].[MachineProducts]  WITH CHECK ADD CHECK  (([Quantity]>=(0)))
GO
ALTER TABLE [dbo].[Products]  WITH CHECK ADD CHECK  (([InStock]>=(0)))
GO
ALTER TABLE [dbo].[Products]  WITH CHECK ADD CHECK  (([MinStock]>=(0)))
GO
ALTER TABLE [dbo].[Products]  WITH CHECK ADD CHECK  (([Price]>(0)))
GO
ALTER TABLE [dbo].[Sales]  WITH CHECK ADD CHECK  (([Quantity]>(0)))
GO
ALTER TABLE [dbo].[Sales]  WITH CHECK ADD CHECK  (([SaleSum]>=(0)))
GO
ALTER TABLE [dbo].[VendingMachines]  WITH CHECK ADD CHECK  (([MaintenanceTimeHours]>=(1) AND [MaintenanceTimeHours]<=(20)))
GO
ALTER TABLE [dbo].[VendingMachines]  WITH CHECK ADD CHECK  (([ResourceHours]>(0)))
GO
ALTER TABLE [dbo].[VendingMachines]  WITH CHECK ADD  CONSTRAINT [CK_CommissioningDate] CHECK  (([DateOfCommissioning]>=[ManufactureDate] AND [DateOfCommissioning]<=[InsertDate]))
GO
ALTER TABLE [dbo].[VendingMachines] CHECK CONSTRAINT [CK_CommissioningDate]
GO
ALTER TABLE [dbo].[VendingMachines]  WITH CHECK ADD  CONSTRAINT [CK_DateOfNextFixing] CHECK  (([DateOfNextFixing]>[InsertDate]))
GO
ALTER TABLE [dbo].[VendingMachines] CHECK CONSTRAINT [CK_DateOfNextFixing]
GO
ALTER TABLE [dbo].[VendingMachines]  WITH CHECK ADD  CONSTRAINT [CK_InventoryDate] CHECK  (([InventoryDate]>=[ManufactureDate] AND [InventoryDate]<=getdate()))
GO
ALTER TABLE [dbo].[VendingMachines] CHECK CONSTRAINT [CK_InventoryDate]
GO
ALTER TABLE [dbo].[VendingMachines]  WITH CHECK ADD  CONSTRAINT [CK_VerificationDate] CHECK  (([LastVerificationDate]>=[ManufactureDate] AND [LastVerificationDate]<=getdate()))
GO
ALTER TABLE [dbo].[VendingMachines] CHECK CONSTRAINT [CK_VerificationDate]
GO
USE [master]
GO
ALTER DATABASE [VendingDB] SET  READ_WRITE 
GO
